spring:
  datasource:
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
    username: ${PGUSER}
    password: ${PGPASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      #ddl-auto: create
      ddl-auto: ${DLLTYPE}

module-name: API no serviço de Cloud da Railway
api-version: 0.9.8
api-description: API do Cloud Railway
api-contact-name: Edson da Silva Freitas
api-contact-url: http://github.com/edsonsfreitas
api-contact-email: edson.s.freitas@gmail.com
springdoc:
  api-docs:
    resolve-schema-properties: true
    swagger-ui:
     csrf:
      enabled=true