logging:
  level:
    root: INFO
    org.springframework.security: DEBUG

spring:
  security:
    web:
      csrf:
        enabled: true
  output:
    ansi:
      enabled: always

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: masterPwd%2.7
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update # validate | update | create | create-drop
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false

module-name: Sistema de Vendas
api-version: 0.9.8
api-description: API do Cloud Railway
api-contact-name: Edson Freitas
api-contact-url: http://github.com/edsonsfreitas
api-contact-email: edson.s.freitas@gmail.com
springdoc:
  api-docs:
    resolve-schema-properties: true
    swagger-ui:
        csrf:
          enabled=true